

# =============== 1.程序数据保存总路径 ===============
data_dir: '../../data_dir'



# =============== 2.重要不可变数据总路径 ===============
important_dir: '重要数据'


# =============== 3.程序统计信息保存分路径 ===============
info_save_dir: 'info_save'


# =============== 4.其他保存数据总路径 ===============
othe_save_dir: 'other_save'

# =============== 5.宏观控制图总路径 ===============
macro_control_chart_dir: 'other_save/macro_control_chart'









